---
# tasks file for sbaerlocher.ohmyzsh

- name: install zsh
  become: true
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - git
    - zsh

- name: clone oh-my-zsh for users
  become: true
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    version: master
    dest: '/home/{{ item.username }}/.zsh'
  with_items: '{{ ohmyzsh_users }}'

- name: Setting default shell per user
  become: true
  user:
    name: '{{ item.username }}'
    shell: /bin/zsh
  with_items: '{{ users }}'

- name: write .zshrc for users
  become: true
  template:
    src: zshrc.j2
    dest: '/home/{{ item.username }}/.zshrc'
    backup: true
    mode: 'u=rw,go=r'
  with_items: '{{ users }}'
